# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 02:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recourses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=recourses.models.image_location)),
            ],
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Recourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=255)),
                ('difficult_education', models.CharField(choices=[('in', 'Iniciantes'), ('me', 'Intermediários'), ('av', 'Avançados'), ('id', 'Indefinido')], default='op', max_length=2)),
                ('difficult_student', models.CharField(choices=[('in', 'Iniciantes'), ('me', 'Intermediários'), ('av', 'Avançados'), ('id', 'Indefinido')], default='op', max_length=2)),
                ('value', models.FloatField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(blank=True, to='recourses.Language')),
                ('recourses', models.ManyToManyField(blank=True, related_name='_recourse_recourses_+', to='recourses.Recourse')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='recourse',
            name='tags',
            field=models.ManyToManyField(blank=True, to='recourses.Tag'),
        ),
        migrations.AddField(
            model_name='pro',
            name='recourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recourses.Recourse'),
        ),
        migrations.AddField(
            model_name='photos',
            name='recourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recourses.Recourse'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recourses.Recourse'),
        ),
        migrations.AddField(
            model_name='con',
            name='recourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recourses.Recourse'),
        ),
    ]
