# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recourses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
