# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 18:58
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recourses', '0003_recourse_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recourse',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title'),
        ),
    ]
