# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recourses', '0004_auto_20170910_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
