# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recourses', '0005_feedback_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recourse',
            name='difficult_education',
            field=models.CharField(choices=[('in', 'Iniciantes'), ('me', 'Intermediários'), ('av', 'Avançados'), ('id', 'Indefinido')], default='id', max_length=2),
        ),
        migrations.AlterField(
            model_name='recourse',
            name='difficult_student',
            field=models.CharField(choices=[('in', 'Iniciantes'), ('me', 'Intermediários'), ('av', 'Avançados'), ('id', 'Indefinido')], default='id', max_length=2),
        ),
    ]
