# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recourses', '0006_auto_20170914_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='anonymous',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
