# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recourses', '0007_auto_20170921_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recourse',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
