# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
