# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20171009_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to=resources.models.image_location)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource')),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='resource',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
