# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20171009_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
