# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20171113_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
