# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 00:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0007_feedback_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deslike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='bad_avaliations',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='good_avaliations',
        ),
        migrations.AddField(
            model_name='feedback',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='deslikes',
            field=models.ManyToManyField(blank=True, to='resources.Deslike'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='likes',
            field=models.ManyToManyField(blank=True, to='resources.Like'),
        ),
        migrations.AddField(
            model_name='resource',
            name='deslikes',
            field=models.ManyToManyField(blank=True, to='resources.Deslike'),
        ),
        migrations.AddField(
            model_name='resource',
            name='likes',
            field=models.ManyToManyField(blank=True, to='resources.Like'),
        ),
    ]
